name: Get SHA with git ls-remote
on: workflow_dispatch

jobs:
  git-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Get sha using git ls-remote
        id: get_sha
        run: |
          sha=$(git ls-remote https://github.com/AstrBotDevs/AstrBot.git refs/heads/master | cut -f1)
          echo "sha=$sha" >> $GITHUB_OUTPUT
          echo ">>> got sha: $sha"
          
      - name: Publish SHA to job summary (visible)
        if: always()
        run: |
          echo "## 🔎 git ls-remote result" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "SHA: ${{ steps.get_sha.outputs.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo ">>>>>> LATEST MASTER SHA: ${{ steps.get_sha.outputs.sha }} <<<<<<"
