name: Get SHA with git ls-remote
on: workflow_dispatch

jobs:
  git-ls:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Get sha using git ls-remote
        id: get_sha
        run: |
          sha=$(git ls-remote https://github.com/AstrBotDevs/AstrBot.git refs/heads/master | cut -f1)
          echo "sha=$sha" >> $GITHUB_OUTPUT
          # 写到 step summary（UI 明显）
          printf "## 🔎 git ls-remote result\n\n**SHA:** `%s`\n\n" "$sha" >> "$GITHUB_STEP_SUMMARY"
          # 大标记输出到日志
          echo ">>>>>> LATEST MASTER SHA: $sha <<<<<<"

      - name: Print sha
        run: echo "sha = ${{ steps.get_sha.outputs.sha }}"
